# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

url: https://ruizinkdojo.com
#url: http://localhost:4000

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"]
highlighter: pygments
markdown: kramdown
google_analytics: UA-68372471-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ruizinkdojo.com

description: ""
author:
  name: Mário Rui Santos
  email: mario.rf.santos@gmail.com
  github: ruizink
  twitter: _ruizink_
  linkedin: mariorfsantos
  disqus-shortname: ruizinkdojo
  bio: Scripting ninja. Automation freak.
  email_md5: 713a89cd06a0535718724b38453ba5b4

rss_path: feed.xml
about_path: about.html

BASE_PATH:

gems: [jekyll-paginate]
